---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s

k3s_control_node: true
k3s_server:
  node-ip: "{{ ansible_host }}"
  tls-san:
    - 157.173.202.8
  docker: false
  write-kubeconfig-mode: "644"
  cluster-cidr: "{{ cluster_cidr }}"
  service-cidr: "{{ service_cidr }}"
  etcd-expose-metrics: true           # Required to monitor etcd with kube-prometheus-stack
  kube-controller-manager-arg:
    - "bind-address=0.0.0.0"          # Required to monitor kube-controller-manager with kube-prometheus-stack
  kube-scheduler-arg:
    - "bind-address=0.0.0.0"          # Required to monitor kube-scheduler with kube-prometheus-stack
  kube-apiserver-arg:
    - "anonymous-auth=true"           # Required for HAProxy health-checks
