apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:4lEECYUfj07ftrtHUq9yrg==,iv:tKct6tsmHHbiBC7xvr03J5eOx8Y8JmfvPidB1e4DswY=,tag:i4OimSE8USNPsOo1BHJLjw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:M7pD5KGWHNxnEsJMvgLcFNsR+gaZ+rT+5JDkSr8jNrhik0iN,iv:vjeBYZ1T6+hOU8a6cZ2an3O7kLYR4T+2AQclJlK2IJ0=,tag:OG/6u1+V5MPCgc7gF62Cpg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:FmVoV4d9K7M=,iv:46tEgi9TIu42u82XtBFY9GN3e3S3DbScIDTRdu75caw=,tag:GyBdfmyARpzWKyPt1u+O8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZVRTczNQVUNTc0RyMjEy
            RmF4b1dEL0ZacDNaYnNtVG5haFd6YzZiOVVVCjBOY3BoVERtcDBHOEpjUVhrd1Nv
            dHBCWmpWak05NStXdEZNNk1vZlRpbnMKLS0tIGorVFNEcUY1SHBLK2pBOHR2R1Ev
            bExjZEJlSGpaWmZ3dE1TMWl6WG4yUDgKFbupVZRYWEIWCQAD3APLZ5LwGkDiz5S3
            RDORQy/93j7zMeLIpLitsag07jZF7EU6vddEfQV1R2FBXO6l2QiLKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-19T16:15:09Z"
    mac: ENC[AES256_GCM,data:2F6GuUxYvJdq6j/Hh2LwQlTrn7OGAvCzZCBCOT+nmZOpr23nSNFPlELopCQeR2ZsHsvXIh/Jzme1IR3TzSFkD1mScb0Y6xgph31A60PG5HdojwGSpF+L8+AT2gIt2Y5yjNo+HSbcxva5jdYqSxVt8Vnd2PANP7lzw6aE5WRGh0k=,iv:ZaS2M+bylV7njCHu5VucGlUTcRkmYYOZvlBW4ZvL32s=,tag:Zd3LzCLiHvbBoDwRejBwIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
