apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:4lEECYUfj07ftrtHUq9yrg==,iv:tKct6tsmHHbiBC7xvr03J5eOx8Y8JmfvPidB1e4DswY=,tag:i4OimSE8USNPsOo1BHJLjw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:1mOgynG8wBqDcaLo9EaN0JDfth4/nJgHvfl6dL0ato37G6B5,iv:2B5SMLrfBFoVc//Qy+D8Bhe2JdhDh4d3arkDXfC8ecU=,tag:Yyde0efkaEugpKRM+Dw67g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:+JD7/0oCKarwfPT0ih7DAWWg+h793ky6,iv:ySQOrEa3JpzRIcT+sUZx26MjL1+afeYZfILga34WLHU=,tag:rreaY3yrWpu1rHmhNPeQmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZVRTczNQVUNTc0RyMjEy
            RmF4b1dEL0ZacDNaYnNtVG5haFd6YzZiOVVVCjBOY3BoVERtcDBHOEpjUVhrd1Nv
            dHBCWmpWak05NStXdEZNNk1vZlRpbnMKLS0tIGorVFNEcUY1SHBLK2pBOHR2R1Ev
            bExjZEJlSGpaWmZ3dE1TMWl6WG4yUDgKFbupVZRYWEIWCQAD3APLZ5LwGkDiz5S3
            RDORQy/93j7zMeLIpLitsag07jZF7EU6vddEfQV1R2FBXO6l2QiLKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-11T21:20:20Z"
    mac: ENC[AES256_GCM,data:8DW6+kTNdgOn4+6qUBRab6NkLuHhSJdmJZQNdoqMGc/0oxb+1Qw3NnOi+QR4dNCvgirIy8pjsAuULplCkGm963THMrPHQe3OfAcrTLF9ioXFDlgz4oH3VUdaWRz58xEPQRRQAMTU5l+7KXPwmD1Zk6iTfMrDgZEUN/8/TOZPzEo=,iv:OWhoIQHreaq+UzUd0vNe572MTUgnwOEaocQ5KStc3jw=,tag:swe8i60GvyT0xCHn9O1RaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
