apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:45bJ2pMYcH3Rfgh9bWBhEiJJtf4wR/e7yPlxrQT7NGzHdkUq,iv:f8sEiUfnx5oS6UB6wMAgDsmw2bjdyfRSjeOiiWOHc9Y=,tag:gGVT06kbYYd73zeqq9Qv5w==,type:str]
    credentials.json: ENC[AES256_GCM,data:oRsfMXuJqGifERblEsyfSVE3RHrQ+HoNEPEBCp3PizYI6RF3tbHPBM/8jJWaK7DuKrVikZ813idnMJEksRv00NaETzAddetHbDhNkHYmOyNhIxoKNmlbUSleR6eCIGMKrMXy9EhbAeHWSEol5kqSvYwtr/OqKfpPAFxPLIOjskXvVNOnipeObl9QeldrLyw0xnXc40hR0hdOfGReGviN6DhzmEZyYNcEQJGAhTmaMw==,iv:tY50SuIWGqRdxO2C8iUsPMiijDejiTfVFnNw1h+DoTw=,tag:sDhuCFEG8SyAAk4SWh7c2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTm8vRVJnZWRtMEU1M1pF
            UlR0UXZRTnRpRnI4bVRFdTNxQ3g2bTUvRVg0CmNiRU9vT2tjeXlBaUs2YmIyVWN5
            T3lwdlFzQ0hYQm90UzRJdHBjcTd0UU0KLS0tIDk1cTdxOStpWmxUSzN6eEIvaVY1
            dGQyc3JXOHdidmg2Z2p6eHdQS0xmenMK8ILOYRMwKi7nlU/rkRCsB4XnJOySOQ5Y
            Q9yoPsFMAmGWELEGr/EliaTeAnVWHsnzk7Znk03Rrg8+E8Wi23udeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-19T16:15:09Z"
    mac: ENC[AES256_GCM,data:7+ywoXPMdB4zWn4bDC7lfUiNBp8pxiZE6xs+3XNtMAetguSs64YYR6zC54H2dEKe2W1E+AqO4uQhht+8e/H/WyoopQJmaC+bu9huVkCGNLVPm9SJfX2In+mQyekY9n6iBpUsIEyLqe/DV4JPSIybGUeBWF+ch840Y0CnbjI/tmo=,iv:SYqt3P6kfLeatSyiyp1uTqulU+0pxE42sEnLFiNilu8=,tag:Rh+ONkYe72zDM2Mdnlkeew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
