apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:/ykpHscJ8knK88GGHJE973wmj+/TL9l/QV/augAy8uATKNEU,iv:t3jcT1iCTUsq0vcoicCutY3zCLAN1HSfegOajCDmSkU=,tag:pmi4T9lN2ZVedQJnmTkJlg==,type:str]
    credentials.json: ENC[AES256_GCM,data:KXlkP6uW9rNn5Urd/8aix1vCghgobCaDqUbs/HWW2Q21nLgKx99LiduOkuGbY5v3s8aYjQKOpR+rUCOEiLp2OUYSKe0OW8bH9L5pFzKLlbOF8/AEm7f5C9PcUwnuX6DqsHNcBTwNOUbNZGH1Gjwh54fVO3bdodt9T1Mcb9+iMr/5AP8Qz54+HKctmW6YNgMEE/EZFcITTWimkn6CA6PfmhEuB4SFuJOo78vCGjzGJA==,iv:umXNnhDMFsu9nFBgBspoBMGgb2y6offMMQcx+Xy8E8Q=,tag:kx+WjCJLhLxWlmHzqTfF1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15nyeuq0zlhyu80tytvwhjdhmpa5mwnclm454cc0trt7ezxrnk37shpeefh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTm8vRVJnZWRtMEU1M1pF
            UlR0UXZRTnRpRnI4bVRFdTNxQ3g2bTUvRVg0CmNiRU9vT2tjeXlBaUs2YmIyVWN5
            T3lwdlFzQ0hYQm90UzRJdHBjcTd0UU0KLS0tIDk1cTdxOStpWmxUSzN6eEIvaVY1
            dGQyc3JXOHdidmg2Z2p6eHdQS0xmenMK8ILOYRMwKi7nlU/rkRCsB4XnJOySOQ5Y
            Q9yoPsFMAmGWELEGr/EliaTeAnVWHsnzk7Znk03Rrg8+E8Wi23udeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-10T19:18:57Z"
    mac: ENC[AES256_GCM,data:aZ+/F/65y44YAi4nZZS3+TOb+i/MIgty23/5NceDuDMwG+u/aseV8CfHYdTdUzc8fIt2aO3ly8+olsPBsIOJ3CHxHAYPim+8OGwd2eA5l0eiqxGNpoHEMoIko27AnpraMUHAWaructtXqUuU2PrO7bXr25dkMwgjBZPrU2eOIhU=,iv:rICicctJREvkdHzK9jAIq2wlBm+yFhWgPtJ7MphO87o=,tag:BlpFmN+S1atENTe+G7EMMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
